// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetSlidesSlidesGetData, GetSlidesSlidesGetResponse, GetBoundingBoxBoxesSlideFilenameGetData, GetBoundingBoxBoxesSlideFilenameGetResponse, GetBoundingBoxBoxesSlideFilenameGetError, SetBoundingBoxBoxesSlideFilenamePutData, SetBoundingBoxBoxesSlideFilenamePutResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Available Slides
 * Retrieves a list of filenames (stems) for all slides found based on the startup pattern.
 */
export const getSlidesSlidesGet = <ThrowOnError extends boolean = false>(options?: Options<GetSlidesSlidesGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetSlidesSlidesGetResponse, unknown, ThrowOnError>({
        url: '/slides',
        ...options
    });
};

/**
 * Get Bounding Box
 * Retrieves the stored bounding box coordinates for a given slide filename (stem).
 */
export const getBoundingBoxBoxesSlideFilenameGet = <ThrowOnError extends boolean = false>(options: Options<GetBoundingBoxBoxesSlideFilenameGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetBoundingBoxBoxesSlideFilenameGetResponse, GetBoundingBoxBoxesSlideFilenameGetError, ThrowOnError>({
        url: '/boxes/{slide_filename}',
        ...options
    });
};

/**
 * Set or Update Bounding Box
 * Sets or updates the bounding box coordinates for a given slide filename (stem).
 */
export const setBoundingBoxBoxesSlideFilenamePut = <ThrowOnError extends boolean = false>(options: Options<SetBoundingBoxBoxesSlideFilenamePutData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<SetBoundingBoxBoxesSlideFilenamePutResponse, unknown, ThrowOnError>({
        url: '/boxes/{slide_filename}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};