// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetSlidesSlidesGetData, GetSlidesSlidesGetResponse, GetBoundingBoxBoxesSlideFilenameGetData, GetBoundingBoxBoxesSlideFilenameGetResponse, GetBoundingBoxBoxesSlideFilenameGetError, SetBoundingBoxBoxesSlideFilenamePutData, SetBoundingBoxBoxesSlideFilenamePutResponse, GetBoxesStatusBoxesStatusGetData, GetBoxesStatusBoxesStatusGetResponse, GetSlideImageSlidesSlideFilenameImageGetData, GetSlideImageSlidesSlideFilenameImageGetResponse, GetSlideImageSlidesSlideFilenameImageGetError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Available Slides
 * Retrieves a list of filenames (stems) for all slides found based on the startup pattern.
 */
export const getSlidesSlidesGet = <ThrowOnError extends boolean = false>(options?: Options<GetSlidesSlidesGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetSlidesSlidesGetResponse, unknown, ThrowOnError>({
        url: '/slides',
        ...options
    });
};

/**
 * Get Bounding Box
 * Retrieves the stored bounding box coordinates for a given slide filename (stem). Returns an empty list if no box is set.
 */
export const getBoundingBoxBoxesSlideFilenameGet = <ThrowOnError extends boolean = false>(options: Options<GetBoundingBoxBoxesSlideFilenameGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetBoundingBoxBoxesSlideFilenameGetResponse, GetBoundingBoxBoxesSlideFilenameGetError, ThrowOnError>({
        url: '/boxes/{slide_filename}',
        ...options
    });
};

/**
 * Set or Update Bounding Box
 * Sets or updates the bounding box coordinates for a given slide filename (stem). Use coords [0,0,0,0] to delete (mark as unlabeled), and [-1,-1,-1,-1] to mark as 'no box needed'.
 */
export const setBoundingBoxBoxesSlideFilenamePut = <ThrowOnError extends boolean = false>(options: Options<SetBoundingBoxBoxesSlideFilenamePutData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<SetBoundingBoxBoxesSlideFilenamePutResponse, unknown, ThrowOnError>({
        url: '/boxes/{slide_filename}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Status of All Boxes
 * Returns the annotation status for all known slides ('labeled', 'unlabeled', 'no_box_needed').
 */
export const getBoxesStatusBoxesStatusGet = <ThrowOnError extends boolean = false>(options?: Options<GetBoxesStatusBoxesStatusGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetBoxesStatusBoxesStatusGetResponse, unknown, ThrowOnError>({
        url: '/boxes/status',
        ...options
    });
};

/**
 * Get Slide Image
 * Retrieves a representative image (macro, thumbnail, or generated) for a slide as base64 PNG.
 */
export const getSlideImageSlidesSlideFilenameImageGet = <ThrowOnError extends boolean = false>(options: Options<GetSlideImageSlidesSlideFilenameImageGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetSlideImageSlidesSlideFilenameImageGetResponse, GetSlideImageSlidesSlideFilenameImageGetError, ThrowOnError>({
        url: '/slides/{slide_filename}/image',
        ...options
    });
};