// This file is auto-generated by @hey-api/openapi-ts

/**
 * Input model for storing bounding box coordinates.
 */
export type BoundingBoxInput = {
    /**
     * Bounding box coordinates [x0, y0, x1, y1].
     */
    coords: [
        number,
        number,
        number,
        number
    ];
};

/**
 * Response model for retrieving bounding box coordinates.
 */
export type BoundingBoxResponse = {
    /**
     * The filename stem of the slide.
     */
    slide_filename: string;
    /**
     * Bounding box coordinates [x0, y0, x1, y1]. Empty list if no box is set. [-1,-1,-1,-1] if marked as 'no box needed'.
     */
    coords?: Array<number>;
};

/**
 * Response model for bulk deidentification operation.
 */
export type BulkDeidentifyResponse = {
    /**
     * Results for each processed slide.
     */
    results: Array<DeidentifyResponse>;
    /**
     * Slides that were skipped due to errors or missing boxes.
     */
    skipped: Array<string>;
};

/**
 * Response model for deidentification operation.
 */
export type DeidentifyResponse = {
    /**
     * The filename stem of the slide.
     */
    slide_filename: string;
    /**
     * Path to the deidentified slide.
     */
    output_path: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Response model for label statistics.
 */
export type LabelStatsResponse = {
    /**
     * Total number of slides
     */
    total: number;
    /**
     * Number of slides that have been labeled
     */
    labeled: number;
    /**
     * Number of slides that are not labeled yet
     */
    unlabeled: number;
    /**
     * Number of slides marked as not needing a box
     */
    no_box_needed: number;
};

/**
 * Response model for returning slide image data.
 */
export type SlideImageResponse = {
    /**
     * The filename stem of the slide.
     */
    slide_filename: string;
    /**
     * Base64 encoded PNG image data.
     */
    image_data: string;
};

/**
 * Response model for listing slide filenames.
 */
export type SlideListResponse = {
    /**
     * List of slide filenames (stems) found.
     */
    slides: Array<string>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type GetSlidesSlidesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/slides';
};

export type GetSlidesSlidesGetResponses = {
    /**
     * Successful Response
     */
    200: SlideListResponse;
};

export type GetSlidesSlidesGetResponse = GetSlidesSlidesGetResponses[keyof GetSlidesSlidesGetResponses];

export type GetBoundingBoxBoxesSlideFilenameGetData = {
    body?: never;
    path: {
        slide_filename: string;
    };
    query?: never;
    url: '/boxes/{slide_filename}';
};

export type GetBoundingBoxBoxesSlideFilenameGetErrors = {
    /**
     * Slide filename not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetBoundingBoxBoxesSlideFilenameGetError = GetBoundingBoxBoxesSlideFilenameGetErrors[keyof GetBoundingBoxBoxesSlideFilenameGetErrors];

export type GetBoundingBoxBoxesSlideFilenameGetResponses = {
    /**
     * Successful Response
     */
    200: BoundingBoxResponse;
};

export type GetBoundingBoxBoxesSlideFilenameGetResponse = GetBoundingBoxBoxesSlideFilenameGetResponses[keyof GetBoundingBoxBoxesSlideFilenameGetResponses];

export type SetBoundingBoxBoxesSlideFilenamePutData = {
    body: BoundingBoxInput;
    path: {
        slide_filename: string;
    };
    query?: never;
    url: '/boxes/{slide_filename}';
};

export type SetBoundingBoxBoxesSlideFilenamePutErrors = {
    /**
     * Slide not found
     */
    404: unknown;
    /**
     * Invalid bounding box data
     */
    422: unknown;
};

export type SetBoundingBoxBoxesSlideFilenamePutResponses = {
    /**
     * Successful Response
     */
    200: BoundingBoxResponse;
};

export type SetBoundingBoxBoxesSlideFilenamePutResponse = SetBoundingBoxBoxesSlideFilenamePutResponses[keyof SetBoundingBoxBoxesSlideFilenamePutResponses];

export type GetBoxesStatusBoxesStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/boxes/status';
};

export type GetBoxesStatusBoxesStatusGetResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type GetBoxesStatusBoxesStatusGetResponse = GetBoxesStatusBoxesStatusGetResponses[keyof GetBoxesStatusBoxesStatusGetResponses];

export type GetLabelStatsLabelStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/label-stats';
};

export type GetLabelStatsLabelStatsGetResponses = {
    /**
     * Successful Response
     */
    200: LabelStatsResponse;
};

export type GetLabelStatsLabelStatsGetResponse = GetLabelStatsLabelStatsGetResponses[keyof GetLabelStatsLabelStatsGetResponses];

export type GetSlideImageSlidesSlideFilenameImageGetData = {
    body?: never;
    path: {
        slide_filename: string;
    };
    query?: never;
    url: '/slides/{slide_filename}/image';
};

export type GetSlideImageSlidesSlideFilenameImageGetErrors = {
    /**
     * Slide not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Error processing slide image
     */
    500: unknown;
};

export type GetSlideImageSlidesSlideFilenameImageGetError = GetSlideImageSlidesSlideFilenameImageGetErrors[keyof GetSlideImageSlidesSlideFilenameImageGetErrors];

export type GetSlideImageSlidesSlideFilenameImageGetResponses = {
    /**
     * Successful Response
     */
    200: SlideImageResponse;
};

export type GetSlideImageSlidesSlideFilenameImageGetResponse = GetSlideImageSlidesSlideFilenameImageGetResponses[keyof GetSlideImageSlidesSlideFilenameImageGetResponses];

export type DeidentifySlideSlidesSlideFilenameDeidentifyPostData = {
    body?: never;
    path: {
        slide_filename: string;
    };
    query?: never;
    url: '/slides/{slide_filename}/deidentify';
};

export type DeidentifySlideSlidesSlideFilenameDeidentifyPostErrors = {
    /**
     * Slide not found
     */
    404: unknown;
    /**
     * Slide has no bounding box defined
     */
    422: unknown;
    /**
     * Error processing slide
     */
    500: unknown;
};

export type DeidentifySlideSlidesSlideFilenameDeidentifyPostResponses = {
    /**
     * Successful Response
     */
    200: DeidentifyResponse;
};

export type DeidentifySlideSlidesSlideFilenameDeidentifyPostResponse = DeidentifySlideSlidesSlideFilenameDeidentifyPostResponses[keyof DeidentifySlideSlidesSlideFilenameDeidentifyPostResponses];

export type DeidentifyAllSlidesSlidesDeidentifyAllPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/slides/deidentify-all';
};

export type DeidentifyAllSlidesSlidesDeidentifyAllPostErrors = {
    /**
     * Error processing slides
     */
    500: unknown;
};

export type DeidentifyAllSlidesSlidesDeidentifyAllPostResponses = {
    /**
     * Successful Response
     */
    200: BulkDeidentifyResponse;
};

export type DeidentifyAllSlidesSlidesDeidentifyAllPostResponse = DeidentifyAllSlidesSlidesDeidentifyAllPostResponses[keyof DeidentifyAllSlidesSlidesDeidentifyAllPostResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};